version: "3.9"
services:
  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   ports:
  #     - '127.0.0.1:5672:5672'
  #     - '127.0.0.1:15672:15672'
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "tookey"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis:/data
volumes:
  postgres:
    driver: local
  redis:
    driver: local